### ISSUE TITLE
save NLTK concordance result to text file 

### ISSUE THREAD

**Issue by alicemai1981** [shrine79/AliceGo#1]
The following code reads text from a website, tokenize the text and use the concordance method of NLTK to search for a certain word.  
The result shall be the word attached with some text before and after it.  for example, search "normally" in text from the link "https://docs.python.org/3/installing/", the result is: 
Displaying 1 of 1 matches:
on < /pre > < /div > < /div > < p > Normally , if a suitable module is already i 

I return the search result to a variable "match". The next task is to write the result to a text document.  however, the write method of the file object only takes string argument.  The type of the "match"is "None".  I understand that A "None" type happens when the function return nothing.   
a post on Stakeoverflow advises that the concordance method prints the result to stdout(not sure what is this?) instead of returning the result.   so must amend the source code of concordance or  redirecting stdout to a file using  contextlib.redirect_stdout(new_target)(only in Python 3.4).  The redirecting way works.  see the second code. 
[https://stackoverflow.com/questions/47649987/how-to-save-nltk-concordance-results-in-a-list](url)
  
-----------------------------------------
`import requests
import nltk
link = "https://docs.python.org/3/installing/"
f = requests.get(link)
words = nltk.Text(nltk.word_tokenize(f.text))
match = words.concordance("normally")
str(match)
f = open("match_result.text", "w")
f.write(match)`
------------------------------------------
error message: 
TypeError: write() argument must be str, not None
------------------------------------------------
`import requests
import nltk
import contextlib
link = "https://docs.python.org/3/installing/"
f = requests.get(link)
with open("match_result.text", "w") as t:
    with contextlib.redirect_stdout(t):
        words = nltk.Text(nltk.word_tokenize(f.text))
        match = words.concordance("normally")`

**Comment by alicemai1981** [comment]
weird format, the "insert code" format looks Ok in editing page, lost all formats once submitted

**Comment by shrine79** [comment]
Why didnt you pick up your mobile?

**Comment by alicemai1981** [comment]
miao
